# Generated by Django 5.2 on 2025-10-18 10:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this blog category.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (max 100 chars). Must be unique.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Auto-generated URL-friendly version of the name.', max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this category from the website.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this brand.', primary_key=True, serialize=False)),
                ('logo', models.ImageField(help_text='Brand logo image. Recommended size: 400x400px with transparent background.', upload_to='brands_logo/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this brand from the website display.')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this department.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Department name (max 150 chars). Must be unique.', max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this department from the system.')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this footer.', primary_key=True, serialize=False)),
                ('singleton_guard', models.BooleanField(default=True, help_text='System field - ensures only one footer exists. Do not modify.', unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo for footer. Recommended size: 400x400px with transparent background.', null=True, upload_to='footer/')),
                ('description', models.CharField(blank=True, help_text='Brief company description (max 280 chars) displayed in footer.', max_length=280)),
                ('address', models.CharField(blank=True, help_text='Company physical address (max 255 chars).', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Contact email address displayed in footer.', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (max 50 chars). Include country code.', max_length=50)),
                ('copyright_name', models.CharField(help_text="Company name for copyright notice (max 120 chars). Example: 'Prime Academy'.", max_length=120)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this hero section.', primary_key=True, serialize=False)),
                ('page_name', models.CharField(help_text="✅ Unique page identifier (max 100 chars). Use lowercase like 'home', 'about-us', 'contact'.", max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Main headline text (max 255 chars) displayed in the hero section.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Subtitle or description text below the main title.', null=True)),
                ('button1_text', models.CharField(blank=True, help_text='Text for the primary call-to-action button (max 100 chars).', max_length=100, null=True)),
                ('button1_url', models.CharField(blank=True, help_text='URL/link for the primary button (max 255 chars). Can be relative (/about) or absolute (https://...).', max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, help_text='Text for the secondary call-to-action button (max 100 chars).', max_length=100, null=True)),
                ('button2_url', models.CharField(blank=True, help_text='URL/link for the secondary button (max 255 chars). Can be relative (/contact) or absolute.', max_length=255, null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Hero background image. Recommended size: 1920x1080px for best quality.', null=True, upload_to='hero_banners/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this hero section from the website.')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['page_name'],
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this SEO configuration.', primary_key=True, serialize=False)),
                ('page_name', models.CharField(help_text="✅ Unique page identifier (max 100 chars). Use lowercase, URL-friendly names like 'home', 'about-us'.", max_length=100, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text="Title tag for search results (max 200 chars, keep under 60). Example: 'Prime Academy - Best Online Courses'", max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text="Description in search results (max 300 chars, keep 150-160). Your 'ad copy' for Google.", max_length=300)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords. Less important for Google now, but can be useful.')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media shares (max 200 chars). Will use Meta Title if empty.', max_length=200)),
                ('og_description', models.TextField(blank=True, help_text='Description for social media (max 300 chars). Will use Meta Description if empty.', max_length=300)),
                ('og_image', models.ImageField(blank=True, help_text='Image for social shares. Recommended: 1200x630 pixels.', null=True, upload_to='seo/og_images/')),
                ('og_type', models.CharField(choices=[('website', 'Website'), ('article', 'Article'), ('product', 'Product')], default='website', help_text="Content type (max 50 chars). 'website' for most pages, 'article' for blog posts.", max_length=50)),
                ('og_url', models.URLField(blank=True, help_text='Permanent URL of the page. Will use Canonical URL if empty.')),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Large Summary'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text="Card type (max 50 chars). 'Summary with Large Image' is usually best.", max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Title for Twitter (max 200 chars). Will use OG Title if empty.', max_length=200)),
                ('twitter_description', models.TextField(blank=True, help_text='Description for Twitter (max 300 chars). Will use OG Description if empty.', max_length=300)),
                ('twitter_image', models.ImageField(blank=True, help_text='Image for Twitter. Recommended: 1200x600 pixels.', null=True, upload_to='seo/twitter_images/')),
                ('twitter_site', models.CharField(blank=True, help_text="Your site's Twitter handle (max 100 chars), e.g., '@PrimeAcademy'.", max_length=100)),
                ('twitter_creator', models.CharField(blank=True, help_text="Author's Twitter handle (max 100 chars), e.g., '@AuthorName'.", max_length=100)),
                ('canonical_url', models.URLField(blank=True, help_text='The single, official URL for this page to prevent duplicate content issues.')),
                ('robots_meta', models.CharField(blank=True, choices=[('index, follow', '✅ Index, Follow (Recommended)'), ('noindex, follow', '🚫 NoIndex, Follow'), ('index, nofollow', '✅ Index, 🚫 NoFollow'), ('noindex, nofollow', '🚫 NoIndex, 🚫 NoFollow')], default='index, follow', help_text='Search engine crawler instructions (max 100 chars).', max_length=100)),
                ('structured_data', models.JSONField(blank=True, help_text='🧠 JSON-LD data. Leave empty to auto-generate on save. You can also paste your custom JSON-LD here to override it.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this SEO configuration.')),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEOs',
                'ordering': ['page_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this skill.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Skill name (max 50 chars). Must be unique. Example: 'Python', 'Web Design'.", max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this skill from selection options.')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this user.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="User's first name (max 150 chars).", max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(help_text="User's last name (max 150 chars).", max_length=150, verbose_name='last name')),
                ('email', models.EmailField(db_index=True, help_text='Unique email address used for login. Must be valid email format.', max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(help_text='Unique phone number (max 15 chars). Include country code.', max_length=15, unique=True, verbose_name='phone number')),
                ('last_password_reset', models.DateTimeField(blank=True, help_text='Timestamp of the last password reset. Auto-managed by system.', null=True)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', help_text="User's role in the system (max 15 chars). Determines access permissions.", max_length=15)),
                ('is_staff', models.BooleanField(default=False, help_text='Check to allow admin site access. Staff can log into admin panel.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable account. Inactive users cannot log in.')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date and time when the user account was created.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Prime Academy User',
                'verbose_name_plural': 'All Users',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this blog post.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Blog post title (max 255 chars). Must be unique.', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Auto-generated URL-friendly version of the title.', max_length=300, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short description/summary (max 500 chars). Used in previews.', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content. Supports HTML and markdown.')),
                ('featured_image', models.ImageField(blank=True, help_text='Main image for the blog post. Recommended size: 1920x1080px.', null=True, upload_to='blog_images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Publication status (max 10 chars). Draft: Not visible to public. Published: Live on website.', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, help_text='Auto-set when status changes to published. Leave empty for drafts.', null=True)),
                ('category', models.ForeignKey(help_text='Select the category for this blog post.', on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='api.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this employee.', primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, help_text='Unique Employee ID (max 50 chars). Example: EMP001, DEV-2024-001', max_length=50, unique=True)),
                ('employee_name', models.CharField(help_text='Full name of the employee (max 50 chars).', max_length=50)),
                ('employee_image', models.ImageField(blank=True, help_text='Employee profile photo. Recommended size: 400x400px.', null=True, upload_to='employee_images/')),
                ('job_title', models.CharField(help_text="Employee's job title or position (max 150 chars).", max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number (max 20 chars).', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text="Employee's email address (max 254 chars).", max_length=254, null=True)),
                ('joining_date', models.DateField(blank=True, help_text='Date when the employee joined the company.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to mark employee as inactive (resigned/terminated).')),
                ('department', models.ForeignKey(help_text='Select the department this employee belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='HeroSlideText',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this slide text.', primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='Text to display in the animated slide (max 255 chars).', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0=first, 1=second, etc.). Lower numbers show first.')),
                ('hero_section', models.ForeignKey(help_text='Select which hero section this text belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.herosection')),
            ],
            options={
                'verbose_name': 'Hero Slide Text',
                'verbose_name_plural': 'Hero Slide Texts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LinkGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this link group.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Column header title (max 100 chars). Example: 'Quick Links', 'Services'.", max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0=first column, 1=second, etc.). Lower numbers appear first.')),
                ('footer', models.ForeignKey(help_text='Footer this link group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='link_groups', to='api.footer')),
            ],
            options={
                'verbose_name': 'Footer Column Group',
                'verbose_name_plural': 'Footer Column Groups',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this quick link.', primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Link text displayed to users (max 80 chars). Example: 'About Us', 'Contact'.", max_length=80)),
                ('url', models.CharField(help_text='Link destination (max 300 chars). Use relative URLs (/about) or absolute (https://...).', max_length=300)),
                ('is_external', models.BooleanField(default=False, help_text='Check if link goes to external website (opens in new tab).')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the group (0=first, 1=second, etc.).')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this link from footer display.')),
                ('group', models.ForeignKey(help_text='Link group this link belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.linkgroup')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this profile.', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text="Professional title or position (max 100 chars). Example: 'Senior Developer'.", max_length=100, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, help_text='Profile picture. Recommended size: 300x300px. Will be automatically optimized.', null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, help_text='Brief personal or professional biography (max 500 chars).', max_length=500, verbose_name='Biography')),
                ('education', models.CharField(blank=True, help_text="Educational background (max 255 chars). Example: 'BSc Computer Science'.", max_length=255, verbose_name='Education')),
                ('user', models.OneToOneField(help_text='Select the user this profile belongs to. Each user can have only one profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, help_text='Select skills associated with this user. Hold Ctrl/Cmd to select multiple.', to='api.skill')),
            ],
            options={
                'verbose_name': 'Prime Academy User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for this social link.', primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('x', 'X/Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('spotify', 'Spotify'), ('thread', 'Thread'), ('pinterest', 'Pinterest'), ('discord', 'Discord'), ('telegram', 'Telegram')], help_text='Select the social media platform.', max_length=20)),
                ('url', models.URLField(help_text='Full URL to your social media profile. Example: https://facebook.com/primeacademy')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0=first icon, 1=second, etc.). Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this social link from footer display.')),
                ('footer', models.ForeignKey(help_text='Footer this social link belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='api.footer')),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
    ]
