# Generated by Django 5.2 on 2025-10-19 13:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Description for Twitter (max 300 chars). Will use OG Description if empty', max_length=300),
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('section_type', models.CharField(choices=[('info', 'Info Section'), ('icon', 'Icon Section')], default='info', help_text='Info Section: Large image with text. Icon Section: Small icon with compact layout.', max_length=10)),
                ('position_choice', models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], default='top', help_text='Position of the section on the page.', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, help_text='Description/text content')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, help_text='Large image for Info Sections, small icon for Icon Sections', null=True, upload_to='content_sections/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='api.pageservice')),
            ],
            options={
                'verbose_name': 'Content Section',
                'verbose_name_plural': 'Content Sections',
                'ordering': ['page', 'order', 'section_type'],
            },
        ),
    ]
