# Generated by Django 5.2.9 on 2025-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontentsection',
            options={'ordering': ['order'], 'verbose_name': 'Course Content Section', 'verbose_name_plural': 'Course Content Sections'},
        ),
        migrations.AlterModelOptions(
            name='coursesectiontab',
            options={'ordering': ['order'], 'verbose_name': 'Course Section Tab', 'verbose_name_plural': 'Course Section Tabs'},
        ),
        migrations.RemoveIndex(
            model_name='coursemodule',
            name='api_coursem_course__9eb5a3_idx',
        ),
        migrations.RenameField(
            model_name='coursecontentsection',
            old_name='course',
            new_name='course_detail',
        ),
        migrations.RenameField(
            model_name='keybenefit',
            old_name='course',
            new_name='course_detail',
        ),
        migrations.RenameField(
            model_name='sideimagesection',
            old_name='course',
            new_name='course_detail',
        ),
        migrations.RenameField(
            model_name='successstory',
            old_name='course',
            new_name='course_detail',
        ),
        migrations.RenameField(
            model_name='whyenrol',
            old_name='course',
            new_name='course_detail',
        ),
        migrations.AlterUniqueTogether(
            name='coursecontentsection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
        migrations.RemoveField(
            model_name='quizquestionoption',
            name='option_image',
        ),
        migrations.AlterField(
            model_name='coursecontentsection',
            name='section_name',
            field=models.CharField(help_text='Name of this section (e.g., Overview, Curriculum)', max_length=100),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='coursecontentsection',
            constraint=models.UniqueConstraint(fields=('course_detail', 'order'), name='unique_section_order_per_course'),
        ),
    ]
