# Generated by Django 5.2.9 on 2025-12-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='slug',
            field=models.SlugField(help_text='URL-friendly module identifier', max_length=120),
        ),
    ]
