# Generated by Django 5.2.9 on 2025-12-08 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='batch',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(help_text='Course the student is enrolled in (auto-set from batch)', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course'),
        ),
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.PositiveIntegerField(help_text='Batch sequence number (1, 2, 3, etc.)')),
                ('batch_name', models.CharField(blank=True, help_text="Optional custom batch name (e.g., 'Winter 2025', 'Weekend Batch')", max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly slug (auto-generated from course + batch number)', max_length=300, unique=True)),
                ('start_date', models.DateField(help_text='When this batch starts')),
                ('end_date', models.DateField(help_text='When this batch ends')),
                ('enrollment_start_date', models.DateField(blank=True, help_text='When enrollment opens (optional, defaults to now)', null=True)),
                ('enrollment_end_date', models.DateField(blank=True, help_text='When enrollment closes (optional, defaults to start_date)', null=True)),
                ('max_students', models.PositiveIntegerField(default=30, help_text='Maximum number of students allowed in this batch')),
                ('enrolled_students', models.PositiveIntegerField(default=0, editable=False, help_text='Current number of enrolled students (auto-calculated)')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price for this batch (optional, overrides course price)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('enrollment_open', 'Enrollment Open'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', help_text='Current status of this batch', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this batch is active and visible')),
                ('description', models.TextField(blank=True, help_text='Batch-specific description or notes (optional)')),
                ('course', models.ForeignKey(help_text='The course this batch is running for', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.course')),
            ],
            options={
                'verbose_name': 'Course Batch',
                'verbose_name_plural': 'Course Batches',
                'ordering': ['-start_date', 'batch_number'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Course batch the student is enrolled in (primary reference)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.coursebatch'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'batch')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['batch', 'is_active'], name='api_enrollm_batch_i_799a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursebatch',
            index=models.Index(fields=['course', 'status', 'is_active'], name='api_courseb_course__35290f_idx'),
        ),
        migrations.AddIndex(
            model_name='coursebatch',
            index=models.Index(fields=['start_date', 'status'], name='api_courseb_start_d_bc04bc_idx'),
        ),
        migrations.AddIndex(
            model_name='coursebatch',
            index=models.Index(fields=['slug'], name='api_courseb_slug_4aa280_idx'),
        ),
        migrations.AddIndex(
            model_name='coursebatch',
            index=models.Index(fields=['status', 'is_active'], name='api_courseb_status_bee92a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursebatch',
            unique_together={('course', 'batch_number')},
        ),
    ]
