# Generated by Django 5.2.9 on 2026-01-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_prefix",
            field=models.CharField(
                db_index=True,
                default="temp",
                help_text="Course prefix. Max Length 8 Characters (UNIQUE, cannot be changed after creation)",
                max_length=8,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course_student_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Course-specific ID: [COURSE_PREFIX]-YYYY-XXX (e.g., CSE-2026-001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["course_student_id"], name="api_enrollm_course__4fa548_idx"),
        ),
    ]
