# Generated by Django 5.2.9 on 2026-01-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={"verbose_name_plural": "Income Payment Methods"},
        ),
    ]
