# Generated by Django 5.2.9 on 2025-12-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("pd", "PDF Document"),
                    ("video", "Video"),
                    ("slide", "Presentation Slides"),
                    ("code", "Code / Project Files"),
                    ("document", "Document"),
                    ("link", "External Link"),
                    ("other", "Other"),
                ],
                default="document",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "Admin"),
                    ("staf", "Staff"),
                    ("accountant", "Accountant"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                ],
                default="student",
                help_text="User's role in the system (max 15 chars). Determines access permissions.",
                max_length=15,
            ),
        ),
    ]
