# Generated by Django 5.2.9 on 2026-01-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_paymentmethod_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={"verbose_name": "Income Payment Method", "verbose_name_plural": "Income Payment Methods"},
        ),
    ]
