# Generated by Django 5.2.9 on 2025-12-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_course_batch_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebatch',
            name='installment_available',
            field=models.BooleanField(blank=True, help_text='Override course installment setting (None = use course default, True = enable, False = disable)', null=True),
        ),
        migrations.AddField(
            model_name='coursebatch',
            name='installment_count',
            field=models.PositiveIntegerField(blank=True, help_text='Batch-specific installment count (overrides course setting if installment_available=True)', null=True),
        ),
    ]
