# Generated by Django 5.2.9 on 2026-01-12 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_course_course_prefix_enrollment_course_student_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("prefix", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prefix", models.CharField(db_index=True, max_length=50, unique=True)),
                ("counter", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "transaction_counter",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("transaction_id", models.CharField(editable=False, max_length=50, unique=True)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("payer_name", models.CharField(max_length=200)),
                ("payer_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("payer_phone", models.CharField(blank=True, max_length=20)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("pending", "Pending"), ("cancelled", "Cancelled")],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("pending", "Pending Approval"), ("rejected", "Rejected")],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_incomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_incomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("income_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.incometype")),
                ("payment_method", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.paymentmethod")),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncomeUpdateRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="update_requests", to="api.income"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_update_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_income_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="income_req_status_idx"),
                    models.Index(fields=["income", "status"], name="income_req_income_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(fields=["-date"], name="income_date_idx"),
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(fields=["status", "approval_status"], name="income_status_idx"),
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(fields=["income_type", "-date"], name="income_type_date_idx"),
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(fields=["payment_method"], name="income_payment_idx"),
        ),
    ]
