# Generated by Django 5.2.9 on 2026-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_paymentmethod_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("partial", "Partial"), ("completed", "Completed"), ("failed", "Failed")],
                db_index=True,
                default="pending",
                help_text="Normalized payment status",
                max_length=20,
            ),
        ),
    ]
