# Generated by Django 5.2.9 on 2025-12-08 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coursebatch_installment_available_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch for enrollment (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coursebatch'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'course', 'batch')},
        ),
    ]
