# Generated by Django 5.2 on 2025-10-21 22:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('faq_nav', models.CharField(max_length=100)),
                ('faq_nav_slug', models.SlugField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['faq_nav', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_name', models.SlugField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms and Conditions'), ('refund', 'Refund Policy'), ('cookie', 'Cookie Policy'), ('data', 'Data Protection Policy'), ('disclaimer', 'Disclaimer'), ('instructor', 'Instructor Agreement'), ('student', 'Student Code of Conduct'), ('copyright', 'Copyright Policy'), ('accessibility', 'Accessibility Policy'), ('payment', 'Payment & Subscription Policy')], unique=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(help_text='Main text content (HTML or plain text)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Policy Related Page',
                'verbose_name_plural': 'Policy Related Pages',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='api.faqitem')),
            ],
            options={
                'ordering': ['category', 'order', 'created_at'],
            },
        ),
    ]
