# Generated by Django 5.2.9 on 2025-12-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cartitem_unique_together_cartitem_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch for enrollment (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coursebatch'),
        ),
    ]
