# Generated by Django 5.2.9 on 2026-01-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_order_payment_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="expenseupdaterequest",
            name="api_expense_status_33bcee_idx",
        ),
        migrations.AlterField(
            model_name="income",
            name="approval_status",
            field=models.CharField(
                choices=[("approved", "Approved"), ("pending", "Pending Approval"), ("rejected", "Rejected")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="expenseupdaterequest",
            index=models.Index(fields=["status", "-created_at"], name="api_expense_status_25fd9e_idx"),
        ),
        migrations.AddConstraint(
            model_name="expenseupdaterequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")), fields=("expense",), name="unique_pending_expense_update"
            ),
        ),
        migrations.AddConstraint(
            model_name="incomeupdaterequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")), fields=("income",), name="unique_pending_income_update"
            ),
        ),
    ]
