# Generated by Django 5.2 on 2025-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_faqitem_policypage_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['item', 'order', 'created_at']},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='category',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='faq_nav_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
