# Generated by Django 5.2.9 on 2025-12-09 18:42

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_batch_to_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Resource title (e.g., 'Week 1 Slides', 'Python Basics Notes')", max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Description of the resource', null=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video'), ('slide', 'Presentation Slides'), ('code', 'Code/Project Files'), ('document', 'Document'), ('link', 'External Link'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Upload file (PDF, ZIP, PPT, etc.)', null=True, upload_to='course_resources/')),
                ('external_url', models.URLField(blank=True, help_text='External link (Google Drive, YouTube, etc.)', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times downloaded')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within module')),
                ('is_active', models.BooleanField(default=True, help_text='Whether resource is visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class', models.ForeignKey(blank=True, help_text='Optional: Link to specific live class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='api.liveclass')),
                ('module', models.ForeignKey(help_text='Module this resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.coursemodule')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Resource',
                'verbose_name_plural': 'Course Resources',
                'ordering': ['module', 'order', '-created_at'],
                'indexes': [models.Index(fields=['module', 'is_active'], name='api_courser_module__ad47af_idx'), models.Index(fields=['live_class'], name='api_courser_live_cl_058694_idx')],
            },
        ),
    ]
