# Generated by Django 5.2.9 on 2026-01-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_expenseupdaterequest_api_expense_status_33bcee_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
