# Generated by Django 5.2 on 2025-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_faq_options_rename_category_faq_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this profile. Disabled profiles cannot be accessed.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, help_text='Custom student ID in format PA-YEAR-01. Only for students.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', help_text="User's role in the system (max 15 chars). Determines access permissions.", max_length=15),
        ),
    ]
