# Generated by Django 5.2.9 on 2025-12-10 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_course_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch this assignment is for (optional - leave blank for all batches)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='api.coursebatch'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch this live class is for (optional - leave blank for all batches)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='api.coursebatch'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch this quiz is for (optional - leave blank for all batches)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='api.coursebatch'),
        ),
    ]
