# Generated by Django 5.2 on 2025-10-25 10:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_is_enabled_customuser_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full blog post content. Supports HTML and markdown.', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short description/summary (max 500 chars). Used in previews.', null=True),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Description/text content'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Write your FAQ answer here.'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(help_text='Write your FAQ question here.'),
        ),
        migrations.AlterField(
            model_name='policypage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Privacy Policy Content', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Write your Biography here.', null=True, verbose_name='Biography'),
        ),
    ]
