# Generated by Django 5.2.9 on 2026-01-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_income_payment_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[("mcq", "Multiple Choice (Single Answer)"), ("multiple", "Multiple Choice (Multiple Answers)")],
                default="mcq",
                max_length=20,
            ),
        ),
    ]
