# Generated by Django 5.2 on 2025-10-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blog_content_alter_blog_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose between image or video for Info Sections', max_length=10),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='video_id',
            field=models.CharField(blank=True, editable=False, help_text='Automatically extracted video ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='video_provider',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], help_text='Select video provider (YouTube or Vimeo)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for video (required when media type is video)', null=True, upload_to='content_sections/video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='video_url',
            field=models.URLField(blank=True, help_text='Full video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID or https://vimeo.com/VIDEO_ID)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='position_choice',
            field=models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom'), ('extra1', 'Extra 1'), ('extra2', 'Extra 2')], default='top', help_text='Position of the section on the page.', max_length=10),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='section_type',
            field=models.CharField(choices=[('info', 'Info Section'), ('icon', 'Icon Section'), ('cta', 'Call To Action')], default='info', help_text='Info Section: Large image with text. Icon Section: Small icon with compact layout.', max_length=10),
        ),
    ]
