# Generated by Django 5.2.9 on 2026-01-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_quizquestion_question_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="correct_answer_text",
        ),
    ]
