# Generated by Django 5.2.9 on 2025-12-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_update_batch_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinstallment',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Any Etxra info metadata (session keys, etc.)'),
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
