# Generated by Django 5.2 on 2025-10-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_contentsection_media_type_contentsection_video_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Get to Know Us', max_length=100)),
                ('description', models.TextField()),
                ('learners_count', models.PositiveIntegerField(default=0)),
                ('learners_short', models.CharField(blank=True, max_length=150, null=True)),
                ('partners_count', models.PositiveIntegerField(default=0)),
                ('partners_short', models.CharField(blank=True, max_length=150, null=True)),
                ('outstanding_title', models.CharField(blank=True, max_length=50, null=True)),
                ('outstanding_short', models.CharField(blank=True, max_length=150, null=True)),
                ('partnerships_title', models.CharField(blank=True, max_length=50, null=True)),
                ('partnerships_short', models.CharField(blank=True, max_length=150, null=True)),
                ('button_text', models.CharField(default='Explore Prime Academy', max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Academy Overview',
                'verbose_name_plural': 'Academy Overview',
            },
        ),
    ]
