# Generated by Django 5.2.9 on 2026-01-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_quizquestion_correct_answer_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizanswer",
            name="answer_text",
        ),
    ]
