# Generated by Django 5.2.9 on 2026-01-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_quizanswer_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="transaction_id",
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
    ]
