# Generated by Django 5.2.9 on 2025-12-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_orderinstallment_extra_data_delete_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Current residential address.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='alternative_contact_phone',
            field=models.CharField(blank=True, help_text='Alternative emergency contact phone number.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Employee blood group (e.g., A+, O-).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Employee’s date of birth.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact person’s name.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contractual', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary'), ('seasonal', 'Seasonal'), ('casual', 'Casual / On-Call'), ('hourly', 'Hourly'), ('freelance', 'Freelance'), ('consultant', 'Consultant'), ('apprentice', 'Apprenticeship'), ('trainee', 'Trainee')], default='full-time', help_text='Type of employment (e.g., Full-time, Part-time, Contract, Internship).', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Years of previous work experience.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', help_text='Employee first name.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text='Gender of the employee (Male, Female, Other).', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this profile. Disabled profiles cannot be accessed.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', help_text='Employee last name.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], help_text='Marital status of the employee.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Employee middle name (optional).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality of the employee.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nid_no',
            field=models.CharField(blank=True, help_text='National ID (NID) number of the employee.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(blank=True, help_text='Highest qualification of the employee.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, help_text='Employee resume/CV file.', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Employee monthly or annual salary.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_name',
            field=models.CharField(blank=True, help_text='Name of employee’s spouse (optional).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text="Employee's work email address.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, help_text='Unique Employee ID. Example: EMP001, DEV-2024-001', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(blank=True, help_text='Employee profile photo. Recommended size 400×400.', null=True, upload_to='employee_images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate employee (resigned/terminated).'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(help_text='Job title or position of the employee.', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary contact phone number.', max_length=20, null=True),
        ),
    ]
