# Generated by Django 5.2 on 2025-10-26 16:00

import uuid

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_academyoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueTab',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text="Tab name (e.g., 'Be The Expert')", max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Value Tab',
                'verbose_name_plural': 'Value Tabs',
                'ordering': ['value_section', 'order'],
            },
        ),
        migrations.AddField(
            model_name='academyoverview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Optional JSON-LD for this blog post. Leave empty to auto-generate.', null=True),
        ),
        migrations.CreateModel(
            name='ValueTabContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose between image or video', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Image for left side', null=True, upload_to='value_tabs/images/')),
                ('video_provider', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], help_text='Video provider (YouTube or Vimeo)', max_length=10, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Full video URL', max_length=500, null=True)),
                ('video_id', models.CharField(blank=True, editable=False, help_text='Automatically extracted video ID', max_length=100, null=True)),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Video thumbnail', null=True, upload_to='value_tabs/video_thumbnails/')),
                ('title', models.CharField(help_text="Content title (e.g., 'BE THE EXPERT')", max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Main content text')),
                ('button_text', models.CharField(blank=True, help_text='Optional button text', max_length=100)),
                ('button_url', models.CharField(blank=True, help_text='Optional button URL', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value_tab', models.OneToOneField(help_text='Each value tab has one content section', on_delete=django.db.models.deletion.CASCADE, related_name='content', to='api.valuetab')),
            ],
            options={
                'verbose_name': 'Value Tab Content',
                'verbose_name_plural': 'Value Tab Contents',
            },
        ),
        migrations.CreateModel(
            name='ValueTabSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text="Section title (e.g., 'OUR VALUES')", max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(help_text='Page this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='value_tab_sections', to='api.pageservice')),
            ],
            options={
                'verbose_name': 'Value Tab Section',
                'verbose_name_plural': 'Value Tab Sections',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.AddField(
            model_name='valuetab',
            name='value_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_tabs', to='api.valuetabsection'),
        ),
        migrations.AlterUniqueTogether(
            name='valuetab',
            unique_together={('value_section', 'slug')},
        ),
    ]
