# Generated by Django 5.2.9 on 2025-12-15 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_employee_employee_name_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesectiontab',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Tab order such as 1 , 2, 3 ...'),
        ),
        migrations.AlterField(
            model_name='orderinstallment',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Any Extra info metadata (session keys, etc.)'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('internal_payment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('settled', 'Settled'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('duplicate', 'Duplicate')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='api.orderinstallment')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gateway_transaction_id'], name='api_payment_gateway_3cc82a_idx'), models.Index(fields=['internal_payment_id'], name='api_payment_interna_bffb2b_idx'), models.Index(fields=['status', 'created_at'], name='api_payment_status_1ddb8d_idx'), models.Index(fields=['installment', 'status'], name='api_payment_install_9added_idx'), models.Index(fields=['request_id'], name='api_payment_request_b0827e_idx')],
                'unique_together': {('installment', 'gateway_transaction_id')},
            },
        ),
    ]
