# Generated by Django 5.2.9 on 2025-12-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_employee_employee_name_employee_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="spouse_contact_phone",
            field=models.CharField(
                blank=True, help_text="Spouse Contact name.", max_length=100, null=True
            ),
        ),
    ]
