# Generated by Django 5.2 on 2025-11-03 21:41

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='api_categor_name_53a3ad_idx'), models.Index(fields=['slug'], name='api_categor_slug_794f78_idx'), models.Index(fields=['is_active'], name='api_categor_is_acti_5fb091_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='Unique course title', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Auto-generated URL-friendly version of the title', max_length=250, unique=True)),
                ('short_description', models.TextField(help_text='Brief description of the course')),
                ('full_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed course description with rich text formatting', null=True)),
                ('header_image', models.ImageField(blank=True, help_text='Course header image', null=True, upload_to='courses/headers/')),
                ('learn_more_url', models.URLField(blank=True, help_text='External URL for more information')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status of the course', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this course is active and visible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.category')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique coupon code (e.g., SAVE20, NEWSTUDENT)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount')], help_text='Type of discount this coupon provides', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('apply_to_all', models.BooleanField(default=False, help_text='Apply to all courses (overrides specific course selection)')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum total uses (leave empty for unlimited)', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum uses per user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon is currently active')),
                ('valid_from', models.DateTimeField(help_text='When this coupon becomes valid')),
                ('valid_until', models.DateTimeField(help_text='When this coupon expires')),
                ('courses', models.ManyToManyField(blank=True, help_text='Specific courses this coupon applies to (leave empty for all courses)', related_name='coupons', to='api.course')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_button', models.CharField(help_text='Text for the hero section button', max_length=100)),
                ('hero_text', models.TextField(help_text='Hero section text content')),
                ('hero_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for detailed hero description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this course detail is active')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='api.course')),
            ],
            options={
                'verbose_name': 'Course Detail',
                'verbose_name_plural': 'Course Details',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseMediaTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('media_url', models.URLField()),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Rich text description for the media tab')),
                ('button_text', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this media tab is active and visible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_tabs', to='api.coursedetail')),
            ],
            options={
                'verbose_name': 'Course Media Tab',
                'verbose_name_plural': 'Course Media Tabs',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('short_description', django_ckeditor_5.fields.CKEditor5Field(help_text='Rich text description of the module')),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether this module is active and visible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.coursedetail')),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price of the course in selected currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('BDT', 'Bangladeshi Taka')], default='BDT', help_text='Currency for pricing', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pricing is currently active')),
                ('is_free', models.BooleanField(default=False, help_text='Mark as free course (overrides all pricing)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed amount discount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_start_date', models.DateTimeField(blank=True, help_text='When discount becomes active', null=True)),
                ('discount_end_date', models.DateTimeField(blank=True, help_text='When discount expires', null=True)),
                ('installment_available', models.BooleanField(default=False, help_text='Whether installment payment is available')),
                ('installment_count', models.PositiveIntegerField(blank=True, help_text='Number of installments allowed', null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='api.course')),
            ],
            options={
                'verbose_name': 'Course Price',
                'verbose_name_plural': 'Course Prices',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Rich text content for the tab')),
                ('is_static', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tab is active and visible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='api.coursedetail')),
            ],
            options={
                'verbose_name': 'Course Tab',
                'verbose_name_plural': 'Course Tabs',
            },
        ),
        migrations.CreateModel(
            name='KeyBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='courses/benefits/')),
                ('title', models.CharField(max_length=100)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(help_text='Rich text description of the benefit')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this benefit is active and visible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='api.coursedetail')),
            ],
            options={
                'verbose_name': 'Key Benefit',
                'verbose_name_plural': 'Key Benefits',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SideImageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='courses/side_sections/')),
                ('title', models.CharField(max_length=200)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(help_text='Rich text content for the side section')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this side image section is active and visible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_image_sections', to='api.coursedetail')),
            ],
            options={
                'verbose_name': 'Side Image Section',
                'verbose_name_plural': 'Side Image Sections',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='courses/stories/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Rich text description of the success story')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this success story is active and visible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to='api.coursedetail')),
            ],
            options={
                'verbose_name': 'Success Story',
                'verbose_name_plural': 'Success Stories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyEnrol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='courses/icons/')),
                ('title', models.CharField(max_length=100)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(help_text='Rich text content explaining why to enroll')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this why enrol section is active and visible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_enrol', to='api.coursedetail')),
            ],
            options={
                'verbose_name': 'Why Enrol Section',
                'verbose_name_plural': 'Why Enrol Sections',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='api_course_title_050021_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_active'], name='api_course_categor_33934d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='api_course_created_6782cf_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='api_coupon_code_f609b1_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='api_coupon_is_acti_6b6f13_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['discount_type'], name='api_coupon_discoun_5e1a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'order'], name='api_coursem_course__d15ada_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='courseprice',
            index=models.Index(fields=['course', 'is_active'], name='api_coursep_course__96f298_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprice',
            index=models.Index(fields=['currency'], name='api_coursep_currenc_7ae9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprice',
            index=models.Index(fields=['is_free'], name='api_coursep_is_free_b7b4b7_idx'),
        ),
    ]
