# Generated by Django 5.2 on 2025-11-04 10:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category_course_coupon_coursedetail_coursemediatab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_lead_instructor', models.BooleanField(default=False, help_text='Mark as lead/primary instructor for this course')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this instructor assignment is currently active')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, help_text='Date when instructor was assigned to this course')),
                ('course', models.ForeignKey(help_text='The course this instructor teaches', on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='api.course')),
                ('modules', models.ManyToManyField(blank=True, help_text='Specific modules this instructor teaches (leave empty if teaching entire course)', related_name='assigned_instructors', to='api.coursemodule')),
                ('teacher', models.ForeignKey(help_text='Teacher assigned as instructor (must have teacher role)', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Instructor',
                'verbose_name_plural': 'Course Instructors',
                'indexes': [models.Index(fields=['course', 'is_active'], name='api_coursei_course__13bd2f_idx'), models.Index(fields=['teacher', 'is_active'], name='api_coursei_teacher_286f6e_idx'), models.Index(fields=['is_lead_instructor'], name='api_coursei_is_lead_5855dc_idx')],
                'unique_together': {('course', 'teacher')},
            },
        ),
    ]
