# Generated by Django 5.2.9 on 2025-12-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_coursesectiontab_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="question_image",
        ),
    ]
