# Generated by Django 5.2.9 on 2025-12-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_quizquestion_question_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='slug',
            field=models.SlugField(default='', help_text='URL-friendly module identifier', max_length=120),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='batch',
            field=models.ForeignKey(default=1, help_text='Specific batch this assignment is for (optional - leave blank for all batches)', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.coursebatch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='batch',
            field=models.ForeignKey(default=1, help_text='Specific batch this live class is for (optional - leave blank for all batches)', on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='api.coursebatch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='batch',
            field=models.ForeignKey(default=1, help_text='Specific batch this quiz is for (optional - leave blank for all batches)', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.coursebatch'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order'), ('course', 'slug')},
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'slug'], name='api_coursem_course__9eb5a3_idx'),
        ),
    ]
