# Generated by Django 5.2 on 2025-11-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_courseinstructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstructor',
            name='instructor_type',
            field=models.CharField(choices=[('lead', 'Lead Instructor'), ('support', 'Support Instructor'), ('assistant', 'Assistant Instructor')], default='lead', help_text='Type of instructor role (lead, support, or assistant)', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='is_lead_instructor',
            field=models.BooleanField(default=False, help_text='Mark as lead/primary instructor for this course (deprecated: use instructor_type)'),
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['instructor_type'], name='api_coursei_instruc_662cba_idx'),
        ),
    ]
