# Generated by Django 5.2.9 on 2025-12-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_coursemodule_unique_together_coursemodule_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='slug',
            field=models.SlugField(help_text='URL-friendly module identifier', max_length=120),
        ),
    ]
