# Generated by Django 5.2 on 2025-11-04 10:49

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_courseinstructor_instructor_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, editable=False, help_text='Unique order number (auto-generated)', max_length=100, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before discounts and taxes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount applied', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount (if applicable)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final total amount to be paid', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='BDT', help_text='Currency code (BDT, USD, etc.)', max_length=3)),
                ('coupon_code', models.CharField(blank=True, help_text='Snapshot of coupon code at time of order', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the order', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('ssl_commerce', 'SSLCommerz'), ('amar_pay', 'Amar Pay'), ('other', 'Other')], help_text='Payment method used', max_length=50)),
                ('payment_id', models.CharField(blank=True, help_text='External payment gateway transaction ID', max_length=255)),
                ('payment_status', models.CharField(blank=True, help_text='Payment gateway status response', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the order was completed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the order was cancelled', null=True)),
                ('billing_email', models.EmailField(help_text='Email for billing and receipts', max_length=254)),
                ('billing_name', models.CharField(help_text='Full name for billing', max_length=200)),
                ('billing_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('billing_address', models.TextField(blank=True, help_text='Billing address (optional)')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (visible to staff only)')),
                ('coupon', models.ForeignKey(blank=True, help_text='Coupon applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.coupon')),
                ('user', models.ForeignKey(help_text='User who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether enrollment is currently active')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the student completed the course', null=True)),
                ('certificate_issued', models.BooleanField(default=False, help_text='Whether certificate has been issued')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Last time student accessed this course', null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(help_text='Course the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course')),
                ('user', models.ForeignKey(help_text='Student enrolled in the course', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Order that created this enrollment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='api.order')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_title', models.CharField(help_text='Snapshot of course title at time of purchase', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Course price at time of purchase', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied to this item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='BDT', help_text='Currency for this item', max_length=3)),
                ('course', models.ForeignKey(help_text='Course being purchased', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='api_order_user_id_536555_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='api_order_order_n_ec9cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='api_order_status_1d49fe_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method'], name='api_order_payment_80590b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'is_active'], name='api_enrollm_user_id_3ffa15_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'is_active'], name='api_enrollm_course__8fe99b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active', 'created_at'], name='api_enrollm_is_acti_142e1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'course'], name='api_orderit_order_i_9dc32d_idx'),
        ),
    ]
