# Generated by Django 5.2 on 2025-11-04 18:05

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_enrollment_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment_plan',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of installments for this order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='installments_paid',
            field=models.PositiveIntegerField(default=0, help_text='Number of installments already paid'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_installment',
            field=models.BooleanField(default=False, help_text='Whether this order uses installment payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='next_installment_date',
            field=models.DateTimeField(blank=True, help_text='Due date for next installment payment', null=True),
        ),
        migrations.CreateModel(
            name='OrderInstallment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField(help_text='Installment sequence number (1, 2, 3...)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this installment', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateTimeField(help_text='When this installment is due')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Payment status of this installment', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When this installment was paid', null=True)),
                ('payment_id', models.CharField(blank=True, help_text='External payment transaction ID for this installment', max_length=255)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used for this installment', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this installment')),
                ('order', models.ForeignKey(help_text='Order this installment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='api.order')),
            ],
            options={
                'verbose_name': 'Order Installment',
                'verbose_name_plural': 'Order Installments',
                'ordering': ['order', 'installment_number'],
                'abstract': False,
                'indexes': [models.Index(fields=['order', 'status'], name='api_orderin_order_i_e42f6b_idx'), models.Index(fields=['due_date', 'status'], name='api_orderin_due_dat_18be85_idx'), models.Index(fields=['status'], name='api_orderin_status_3ea67d_idx')],
                'unique_together': {('order', 'installment_number')},
            },
        ),
    ]
