# Generated by Django 5.2 on 2025-11-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_installment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_payment_description',
            field=models.TextField(blank=True, help_text="Description of custom payment (e.g., 'Workshop fee', 'Consultation')"),
        ),
        migrations.AddField(
            model_name='order',
            name='is_custom_payment',
            field=models.BooleanField(default=False, help_text='Whether this is a custom payment (not course-based)'),
        ),
    ]
