# Generated by Django 5.2 on 2025-11-04 18:40

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_custom_payment_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(db_index=True, editable=False, help_text='Unique payment reference number (CPAY-YYYYMMDD-XXXXX)', max_length=100, unique=True)),
                ('title', models.CharField(help_text="Payment title (e.g., 'Scholarship Enrollment', 'Staff Training')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Reason for custom payment (scholarship, discount, etc.)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Custom payment amount (can be 0 for free enrollment)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original course price (for reference)', max_digits=10, null=True)),
                ('currency', models.CharField(default='BDT', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('ssl_commerce', 'SSLCommerz'), ('amar_pay', 'Amar Pay'), ('cash', 'Cash'), ('free', 'Free/Scholarship'), ('other', 'Other')], help_text='Payment method used', max_length=50)),
                ('payment_id', models.CharField(blank=True, help_text='External payment gateway transaction ID', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When payment was cancelled', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (staff only)')),
                ('course', models.ForeignKey(blank=True, help_text='Course for enrollment (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_payments', to='api.course')),
                ('created_by', models.ForeignKey(help_text='Admin who created this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_custom_payments', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(blank=True, help_text='Associated enrollment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_payment', to='api.enrollment')),
                ('student', models.ForeignKey(help_text='Student being enrolled', on_delete=django.db.models.deletion.CASCADE, related_name='custom_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Payment',
                'verbose_name_plural': 'Custom Payments',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['student', 'status'], name='api_customp_student_a91946_idx'), models.Index(fields=['course', 'status'], name='api_customp_course__7cc057_idx'), models.Index(fields=['payment_number'], name='api_customp_payment_b77dd4_idx'), models.Index(fields=['created_by', 'created_at'], name='api_customp_created_167ab5_idx'), models.Index(fields=['status', 'created_at'], name='api_customp_status_25e4e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, editable=False, help_text='Unique registration number (EVT-YYYYMMDD-XXXXX)', max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('training', 'Training'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('conference', 'Conference'), ('meetup', 'Meetup'), ('bootcamp', 'Bootcamp'), ('other', 'Other')], db_index=True, default='workshop', help_text='Type of event', max_length=20)),
                ('event_name', models.CharField(help_text='Name of the event', max_length=255)),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('event_location', models.CharField(blank=True, help_text='Event location (physical or virtual)', max_length=255)),
                ('event_description', models.TextField(blank=True, help_text='Event description and details')),
                ('ticket_type', models.CharField(default='General Admission', help_text='Type of ticket (e.g., VIP, Early Bird, Student)', max_length=100)),
                ('number_of_tickets', models.PositiveIntegerField(default=1, help_text='Number of tickets purchased')),
                ('price_per_ticket', models.DecimalField(decimal_places=2, help_text='Price per ticket', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount (price × tickets)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='BDT', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('ssl_commerce', 'SSLCommerz'), ('amar_pay', 'Amar Pay'), ('cash', 'Cash'), ('free', 'Free'), ('other', 'Other')], help_text='Payment method used', max_length=50)),
                ('payment_id', models.CharField(blank=True, help_text='External payment gateway transaction ID', max_length=255)),
                ('is_attended', models.BooleanField(default=False, help_text='Whether attendee showed up')),
                ('attended_at', models.DateTimeField(blank=True, help_text='When attendance was recorded', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When registration was cancelled', null=True)),
                ('contact_name', models.CharField(help_text='Full name for registration', max_length=200)),
                ('contact_email', models.EmailField(help_text='Email for registration and updates', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (staff only)')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this registration (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_event_registrations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User registering for event', on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-event_date', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'status'], name='api_eventre_user_id_515e10_idx'), models.Index(fields=['registration_number'], name='api_eventre_registr_cf4032_idx'), models.Index(fields=['event_type', 'event_date'], name='api_eventre_event_t_77d570_idx'), models.Index(fields=['event_date', 'status'], name='api_eventre_event_d_9aa3b4_idx'), models.Index(fields=['status', 'created_at'], name='api_eventre_status_1cd856_idx'), models.Index(fields=['created_by', 'created_at'], name='api_eventre_created_0ef42e_idx')],
            },
        ),
    ]
