# Generated by Django 5.2 on 2025-11-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_custompayment_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompayment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this payment record is active'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this registration is active'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this order is active'),
        ),
        migrations.AddField(
            model_name='orderinstallment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this installment is active'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this order item is active'),
        ),
    ]
