# Generated by Django 5.2 on 2025-11-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_is_active_to_custom_payment_and_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_in_megamenu',
            field=models.BooleanField(default=False, help_text='Whether to display this course in the megamenu'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Rich text content for detailed hero description', null=True),
        ),
    ]
