# Generated by Django 5.2 on 2025-11-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_course_show_in_megamenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_in_home_tab',
            field=models.BooleanField(default=False, help_text='Whether to display this course in the home tab (homepage category blocks)'),
        ),
    ]
