# Generated by Django 5.2 on 2025-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_course_show_in_home_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_megamenu',
            field=models.BooleanField(default=False, help_text='Whether this category should appear in the site megamenu'),
        ),
    ]
