# Generated by Django 5.2 on 2025-11-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_category_show_in_megamenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course Coupon', 'verbose_name_plural': 'Course Coupons'},
        ),
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['order'], 'verbose_name': 'Course Module/Chapter', 'verbose_name_plural': 'Course Modules/Chapters'},
        ),
        migrations.AlterModelOptions(
            name='coursetab',
            options={'verbose_name': 'Course Content Tab', 'verbose_name_plural': 'Course Content Tabs'},
        ),
        migrations.AlterModelOptions(
            name='keybenefit',
            options={'verbose_name': 'Course Key Benefit', 'verbose_name_plural': 'Course Key Benefits'},
        ),
        migrations.AlterModelOptions(
            name='sideimagesection',
            options={'verbose_name': 'Course Side Image Section', 'verbose_name_plural': 'Course Side Image Sections'},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'verbose_name': 'Course Success Story', 'verbose_name_plural': 'Course Success Stories'},
        ),
        migrations.AlterModelOptions(
            name='whyenrol',
            options={'verbose_name': 'Course Why Enrol Section', 'verbose_name_plural': 'Course Why Enrol Sections'},
        ),
    ]
