# Generated by Django 5.2 on 2025-11-09 20:58

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_update_course_verbose_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetab',
            name='course',
        ),
        migrations.CreateModel(
            name='CourseContentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(help_text="Name of this section (e.g., 'Overview', 'Curriculum', 'Features')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of sections')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is active and visible')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='api.coursedetail')),
            ],
            options={
                'verbose_name': 'Course Content Section',
                'verbose_name_plural': 'Course Content Sections',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CourseSectionTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tab_name', models.CharField(help_text='Name of this tab (shown as tab header)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tab order (0 or 1, max 2 tabs per section)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tab is active and visible')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='api.coursecontentsection')),
            ],
            options={
                'verbose_name': 'Course Section Tab',
                'verbose_name_plural': 'Course Section Tabs',
                'ordering': ['section', 'order'],
                'unique_together': {('section', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CourseTabbedContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose between image or video', max_length=10)),
                ('title', models.CharField(help_text='Title of this content item', max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text description/content')),
                ('button_text', models.CharField(blank=True, help_text='Optional button text', max_length=100)),
                ('button_link', models.CharField(blank=True, help_text='Optional button link', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image for this content item', null=True, upload_to='courses/content/images/')),
                ('video_provider', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], help_text='Select video provider (YouTube or Vimeo)', max_length=10, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Full video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)', max_length=500, null=True)),
                ('video_id', models.CharField(blank=True, editable=False, help_text='Automatically extracted video ID', max_length=100, null=True)),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Thumbnail for video (required when media type is video)', null=True, upload_to='courses/content/video_thumbnails/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the tab')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this content is active and visible')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.coursesectiontab')),
            ],
            options={
                'verbose_name': 'Course Tabbed Content',
                'verbose_name_plural': 'Course Tabbed Contents',
                'ordering': ['tab', 'order'],
                'abstract': False,
                'unique_together': {('tab', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='CourseMediaTab',
        ),
        migrations.DeleteModel(
            name='CourseTab',
        ),
    ]
