# Generated by Django 5.2 on 2025-11-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_course_content_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetabbedcontent',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for this content item (required for image type, optional for video as poster)', null=True, upload_to='courses/content/images/'),
        ),
        migrations.AlterField(
            model_name='coursetabbedcontent',
            name='title',
            field=models.CharField(blank=True, help_text='Title of this content item', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursetabbedcontent',
            name='video_provider',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], help_text='Video provider: YouTube or Vimeo (for video type OR image with video popup)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursetabbedcontent',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Video thumbnail (required only when media_type is video)', null=True, upload_to='courses/content/video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='coursetabbedcontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Full video URL - auto-extracts ID (for video type OR image with video popup)', max_length=500, null=True),
        ),
    ]
