# Generated by Django 5.2 on 2025-11-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_coursetabbedcontent_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='learn_more_url',
        ),
    ]
