# Generated by Django 5.2 on 2025-11-10 19:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_cart_cartitem_wishlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Assignment title', max_length=200)),
                ('description', models.TextField(help_text='Assignment instructions and requirements')),
                ('attachment_file', models.FileField(blank=True, help_text='Optional attachment (PDF, DOCX, etc.)', null=True, upload_to='assignments/instructions/')),
                ('due_date', models.DateTimeField(blank=True, help_text='Assignment due date (optional)', null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum score for this assignment', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Minimum score required to pass', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('allow_late_submission', models.BooleanField(default=True, help_text='Allow submissions after due date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is active and counts toward completion')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order within module')),
                ('module', models.ForeignKey(help_text='Module this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.coursemodule')),
            ],
            options={
                'verbose_name': 'Module Assignment',
                'verbose_name_plural': 'Module Assignments',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleQuiz',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Quiz title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Quiz instructions or description')),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Minimum score required to pass (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed (0 = unlimited)')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (leave empty for no limit)', null=True)),
                ('questions', models.JSONField(default=list, help_text='Quiz questions in JSON format')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this quiz is active and counts toward completion')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order within module')),
                ('module', models.ForeignKey(help_text='Module this quiz belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.coursemodule')),
            ],
            options={
                'verbose_name': 'Module Quiz',
                'verbose_name_plural': 'Module Quizzes',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignmentSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_file', models.FileField(blank=True, help_text='Uploaded assignment file', null=True, upload_to='assignments/submissions/')),
                ('submission_text', models.TextField(blank=True, help_text='Text submission or notes')),
                ('submission_url', models.URLField(blank=True, help_text='External link (GitHub, Google Drive, etc.)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When assignment was submitted')),
                ('is_late', models.BooleanField(default=False, help_text='Whether submission was after due date')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score awarded by teacher', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, help_text='Teacher feedback on submission')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Needs Resubmission')], default='pending', help_text='Submission status', max_length=20)),
                ('graded_at', models.DateTimeField(blank=True, help_text='When assignment was graded', null=True)),
                ('resubmission_count', models.PositiveIntegerField(default=0, help_text='Number of times this was resubmitted')),
                ('assignment', models.ForeignKey(help_text='Assignment being submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.moduleassignment')),
                ('graded_by', models.ForeignKey(blank=True, help_text='Teacher who graded this submission', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who submitted this assignment', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Assignment Submission',
                'verbose_name_plural': 'Student Assignment Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentModuleProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether student completed this module')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When module was marked complete', null=True)),
                ('notes', models.TextField(blank=True, help_text='Teacher notes on student progress')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Teacher who marked module as complete', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_module_completions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(help_text='Module being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='api.coursemodule')),
                ('student', models.ForeignKey(help_text='Student whose progress is tracked', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Module Progress',
                'verbose_name_plural': 'Student Module Progress',
                'ordering': ['module__order'],
            },
        ),
        migrations.CreateModel(
            name='StudentQuizAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict, help_text='Student answers in JSON format')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Score achieved (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_passed', models.BooleanField(default=False, help_text='Whether student passed (score >= passing_score)')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Attempt number for this student on this quiz')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When quiz attempt started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When quiz was completed', null=True)),
                ('graded_at', models.DateTimeField(blank=True, help_text='When quiz was graded', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Teacher feedback on quiz performance')),
                ('graded_by', models.ForeignKey(blank=True, help_text='Teacher who graded this attempt (for manual grading)', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quizzes', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(help_text='Quiz that was attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.modulequiz')),
                ('student', models.ForeignKey(help_text='Student who took this quiz', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Quiz Attempt',
                'verbose_name_plural': 'Student Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overall completion percentage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('modules_completed', models.PositiveIntegerField(default=0, help_text='Number of modules completed')),
                ('modules_total', models.PositiveIntegerField(default=0, help_text='Total number of active modules')),
                ('quizzes_passed', models.PositiveIntegerField(default=0, help_text='Number of quizzes passed')),
                ('quizzes_total', models.PositiveIntegerField(default=0, help_text='Total number of active quizzes')),
                ('assignments_completed', models.PositiveIntegerField(default=0, help_text='Number of assignments approved')),
                ('assignments_total', models.PositiveIntegerField(default=0, help_text='Total number of active assignments')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether student completed 100% of course')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When course was completed', null=True)),
                ('certificate_issued', models.BooleanField(default=False, help_text='Whether completion certificate was issued')),
                ('certificate_issued_at', models.DateTimeField(blank=True, help_text='When certificate was issued', null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last time progress was updated')),
                ('course', models.ForeignKey(help_text='Course being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='api.course')),
                ('enrollment', models.OneToOneField(blank=True, help_text='Related enrollment record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.enrollment')),
                ('student', models.ForeignKey(help_text='Student whose progress is tracked', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Progress',
                'verbose_name_plural': 'Course Progress Records',
                'ordering': ['-last_activity_at'],
                'indexes': [models.Index(fields=['student', 'course'], name='api_coursep_student_235e81_idx'), models.Index(fields=['course', 'is_completed'], name='api_coursep_course__4a720d_idx'), models.Index(fields=['student', 'is_completed'], name='api_coursep_student_5873de_idx'), models.Index(fields=['-last_activity_at'], name='api_coursep_last_ac_61dc90_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='moduleassignment',
            index=models.Index(fields=['module', 'is_active'], name='api_modulea_module__377028_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleassignment',
            index=models.Index(fields=['due_date'], name='api_modulea_due_dat_88e51a_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleassignment',
            index=models.Index(fields=['order'], name='api_modulea_order_97f353_idx'),
        ),
        migrations.AddIndex(
            model_name='modulequiz',
            index=models.Index(fields=['module', 'is_active'], name='api_moduleq_module__49db72_idx'),
        ),
        migrations.AddIndex(
            model_name='modulequiz',
            index=models.Index(fields=['order'], name='api_moduleq_order_aa46f2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignmentsubmission',
            index=models.Index(fields=['student', 'assignment'], name='api_student_student_882055_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='api_student_assignm_9343a3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignmentsubmission',
            index=models.Index(fields=['-submitted_at'], name='api_student_submitt_f5a1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignmentsubmission',
            index=models.Index(fields=['status'], name='api_student_status_ac83c0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmoduleprogress',
            index=models.Index(fields=['student', 'module'], name='api_student_student_7b0148_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmoduleprogress',
            index=models.Index(fields=['module', 'is_completed'], name='api_student_module__ca1ace_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmoduleprogress',
            index=models.Index(fields=['student', 'is_completed'], name='api_student_student_91e07b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmoduleprogress',
            unique_together={('student', 'module')},
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['student', 'quiz'], name='api_student_student_3aaf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['quiz', 'is_passed'], name='api_student_quiz_id_a1f79c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['-started_at'], name='api_student_started_0303f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentquizattempt',
            unique_together={('student', 'quiz', 'attempt_number')},
        ),
    ]
