# Generated by Django 5.2 on 2025-11-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_moduleassignment_modulequiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulequiz',
            name='external_url',
            field=models.URLField(blank=True, help_text='External quiz URL (Google Forms, Typeform, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='modulequiz',
            name='instructions',
            field=models.TextField(blank=True, help_text='Additional instructions for students'),
        ),
        migrations.AddField(
            model_name='modulequiz',
            name='quiz_type',
            field=models.CharField(choices=[('built_in', 'Built-in Quiz'), ('external', 'External Link')], default='built_in', help_text='Quiz type: built-in or external link', max_length=20),
        ),
        migrations.AddField(
            model_name='modulequiz',
            name='show_correct_answers',
            field=models.BooleanField(default=True, help_text='Show correct answers after submission'),
        ),
        migrations.AddField(
            model_name='modulequiz',
            name='shuffle_options',
            field=models.BooleanField(default=False, help_text='Randomize answer options'),
        ),
        migrations.AddField(
            model_name='modulequiz',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Randomize question order for each student'),
        ),
        migrations.AddField(
            model_name='modulequiz',
            name='total_points',
            field=models.PositiveIntegerField(default=100, help_text='Total points available in quiz'),
        ),
        migrations.AlterField(
            model_name='modulequiz',
            name='questions',
            field=models.JSONField(blank=True, default=dict, help_text='Quiz questions in JSON format (for built-in quizzes)'),
        ),
    ]
