# Generated by Django 5.2 on 2025-11-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_quiz_builder_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='Dhaka', help_text='Billing city', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='Bangladesh', help_text='Billing country', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postcode',
            field=models.CharField(default='1207', help_text='Billing postal/ZIP code', max_length=20),
        ),
    ]
