# Generated by Django 5.2 on 2025-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_order_billing_city_order_billing_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch',
            field=models.SmallIntegerField(default=0, help_text='Batch number for versioning or grouping courses'),
        ),
    ]
