# Generated by Django 5.2 on 2025-11-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_course_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show_in_home_latest',
            field=models.BooleanField(default=True, help_text="Show this blog in the 'Latest Blogs' section on the home page. Only applies to published blogs."),
        ),
    ]
