# Generated by Django 5.2 on 2025-11-25 21:31

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_show_in_home_latest_to_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed assignment instructions and requirements')),
                ('assignment_type', models.CharField(choices=[('written', 'Written Assignment'), ('coding', 'Coding Assignment'), ('project', 'Project'), ('quiz', 'Quiz'), ('presentation', 'Presentation')], default='written', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='Reference materials or assignment file', null=True, upload_to='assignments/attachments/')),
                ('total_marks', models.PositiveIntegerField(default=100, help_text='Maximum marks for this assignment')),
                ('passing_marks', models.PositiveIntegerField(default=40, help_text='Minimum marks required to pass')),
                ('due_date', models.DateTimeField(help_text='Submission deadline')),
                ('late_submission_allowed', models.BooleanField(default=True, help_text='Allow submissions after due date')),
                ('late_submission_penalty', models.PositiveIntegerField(default=10, help_text='Percentage penalty for late submission')),
                ('order', models.PositiveIntegerField(help_text='Order of this assignment within the module')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignments', to='api.coursemodule')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Description of what will be covered in this live class', null=True)),
                ('scheduled_date', models.DateTimeField(help_text='Date and time when the live class is scheduled')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of the live class in minutes')),
                ('meeting_url', models.URLField(blank=True, help_text='URL for the live class (Zoom, Google Meet, etc.)')),
                ('meeting_id', models.CharField(blank=True, help_text='Meeting ID or room code', max_length=100)),
                ('meeting_password', models.CharField(blank=True, help_text='Password for the meeting', max_length=50)),
                ('recording_url', models.URLField(blank=True, help_text='URL of the recorded session (available after class)', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('order', models.PositiveIntegerField(help_text='Order of this live class within the module')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classes', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='api.coursemodule')),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Instructions and overview for the quiz', null=True)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('passing_marks', models.PositiveIntegerField(default=40)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Time limit for the quiz in minutes')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Show correct answers after submission')),
                ('randomize_questions', models.BooleanField(default=False, help_text='Randomize question order for each attempt')),
                ('available_from', models.DateTimeField(blank=True, help_text='When the quiz becomes available', null=True)),
                ('available_until', models.DateTimeField(blank=True, help_text='When the quiz closes', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_quizzes', to='api.coursemodule')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['module', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Which attempt this is (1, 2, 3...)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='in_progress', max_length=20)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.quiz')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='module_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', django_ckeditor_5.fields.CKEditor5Field(help_text='The question text (supports rich formatting)')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice (Single Answer)'), ('multiple', 'Multiple Choice (Multiple Answers)'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='mcq', max_length=20)),
                ('question_image', models.ImageField(blank=True, help_text='Optional image for the question', null=True, upload_to='quizzes/questions/')),
                ('marks', models.PositiveIntegerField(default=1, help_text='Points for this question')),
                ('order', models.PositiveIntegerField(help_text='Display order of the question')),
                ('correct_answer_text', models.TextField(blank=True, help_text='Expected answer for short answer questions')),
                ('explanation', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explanation shown after answering', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['quiz', 'order'],
                'unique_together': {('quiz', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.TextField(help_text='The answer option text')),
                ('option_image', models.ImageField(blank=True, help_text='Optional image for this option', null=True, upload_to='quizzes/options/')),
                ('is_correct', models.BooleanField(default=False, help_text='Check if this is a correct answer')),
                ('order', models.PositiveIntegerField(help_text='Display order of the option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Question Option',
                'verbose_name_plural': 'Quiz Question Options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Text answer or description', null=True)),
                ('submission_file', models.FileField(blank=True, help_text='Uploaded assignment file', null=True, upload_to='assignments/submissions/')),
                ('submission_url', models.URLField(blank=True, help_text='URL for online submissions (GitHub, Google Drive, etc.)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False, help_text='Whether this submission was after the deadline')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('resubmit', 'Needs Resubmission')], default='submitted', max_length=20)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded by instructor', max_digits=6, null=True)),
                ('feedback', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Instructor's feedback", null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.assignment')),
                ('graded_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_graded_assignments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='module_assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='LiveClassAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attended', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='How long the student attended (in minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.liveclass')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Class Attendance',
                'verbose_name_plural': 'Live Class Attendances',
                'unique_together': {('live_class', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, help_text='Text answer (for short answer/essay questions)')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct (auto-graded for MCQ)')),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, help_text='Marks given for this answer', max_digits=6)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quizquestion')),
                ('selected_options', models.ManyToManyField(blank=True, help_text='Selected answer options (for MCQ)', to='api.quizquestionoption')),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'verbose_name_plural': 'Quiz Answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
