"""
Export utilities for CSV and PDF generation.
"""

import os
import csv
from datetime import datetime
from io import BytesIO

from django.conf import settings
from django.http import HttpResponse

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

try:
    from reportlab.graphics.barcode import qr
except ImportError:
    qr = None


# ============================================================================
# CSV EXPORTER
# ============================================================================

class CSVExporter:
    @staticmethod
    def export_to_csv(filename, headers, data):
        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = f'attachment; filename="{filename}"'

        writer = csv.writer(response)
        writer.writerow(headers)

        for row in data:
            writer.writerow(row)

        return response


# ============================================================================
# PDF EXPORTER (GLOBAL FOOTER ENABLED)
# ============================================================================
class PDFExporter:
    """Reusable PDF exporter with footer, page numbers, and repeating headers."""

    def __init__(self, title=None, pagesize=A4, logo_path=None):
        self.title = title
        self.pagesize = pagesize

        # Auto-detect logo if not provided
        if logo_path is None:
            logo_path = os.path.join(
                settings.BASE_DIR,
                "core/static/default_images/prime-academy-logo.jpg"
            )

        self.logo_path = logo_path if os.path.exists(logo_path) else None
        self.styles = getSampleStyleSheet()
        self._add_styles()

    # -----------------------------
    # STYLES
    # -----------------------------
    def _add_styles(self):
        if "CustomTitle" not in self.styles:
            self.styles.add(
                ParagraphStyle(
                    name="CustomTitle",
                    fontSize=20,
                    fontName="Helvetica-Bold",
                    alignment=TA_CENTER,
                    spaceAfter=12,
                )
            )

        if "CustomHeading" not in self.styles:
            self.styles.add(
                ParagraphStyle(
                    name="CustomHeading",
                    fontSize=13,
                    fontName="Helvetica-Bold",
                    spaceAfter=8,
                    textColor=colors.HexColor("#053867"),
                )
            )

        if "CustomBody" not in self.styles:
            self.styles.add(
                ParagraphStyle(
                    name="CustomBody",
                    fontSize=10,
                    textColor=colors.HexColor("#333333"),
                )
            )

    # -----------------------------
    # FOOTER (WITH PAGE NUMBERS)
    # -----------------------------
    def _footer(self, canvas, doc):
        canvas.saveState()

        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#666666"))

        # Left
        canvas.drawString(
            doc.leftMargin,
            12,
            "Generated by Prime Academy",
        )

        # Center
        canvas.setFont("Helvetica-Oblique", 7)
        canvas.drawCentredString(
            doc.pagesize[0] / 2,
            5,
            "This is a system-generated document. No signature is required.",
        )

        # Right (Just Page Number)
        page_text = f"Page {canvas.getPageNumber()}"
        canvas.setFont("Helvetica", 8)
        canvas.drawRightString(
            doc.pagesize[0] - doc.rightMargin,
            12,
            page_text,
        )

        canvas.restoreState()

    # -----------------------------
    # CREATE PDF
    # -----------------------------
    def create_pdf(self, content):
        buffer = BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            pagesize=self.pagesize,
            leftMargin=36,
            rightMargin=36,
            topMargin=24,
            bottomMargin=28,
            title=self.title,
        )

        story = []

        # Add logo if provided
        if self.logo_path and os.path.exists(self.logo_path):
            try:
                logo = Image(self.logo_path)
                logo.drawWidth = 110
                logo.drawHeight = 110 * (301 / 829)  # keep ratio
                logo.hAlign = 'CENTER'
                story.append(logo)
                story.append(Spacer(1, 6))
            except Exception as e:
                # If logo fails to load, continue without it
                pass

        if self.title:
            story.append(Paragraph(self.title, self.styles["Title"]))
            story.append(Spacer(1, 6))

        story.extend(content)

        doc.build(
            story,
            onFirstPage=self._footer,
            onLaterPages=self._footer,
        )

        buffer.seek(0)
        response = HttpResponse(buffer.read(), content_type="application/pdf")
        filename = (self.title or "export").replace(" ", "_")
        response["Content-Disposition"] = f'attachment; filename="{filename}.pdf"'
        return response

    # -----------------------------
    # TABLE (REPEATING HEADER)
    # -----------------------------
    def create_table(self, headers, data, col_widths=None):
        table = Table(
            [headers] + data,
            colWidths=col_widths,
            repeatRows=1,  # ✅ HEADER REPEATS ON EVERY PAGE
        )

        table.setStyle(
            TableStyle(
                [
                    # Header
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#053867")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 10),
                    ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

                    # Body
                    ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                    ("TEXTCOLOR", (0, 1), (-1, -1), colors.black),
                    ("FONTSIZE", (0, 1), (-1, -1), 9),
                    ("ALIGN", (0, 1), (-1, -1), "CENTER"),
                    ("TOPPADDING", (0, 1), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 1), (-1, -1), 6),

                    # Grid
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
                ]
            )
        )

        return table
